### ISSUE TITLE
Implement Advanced Search Capabilities

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/search-maven-org#1]
**Description**

Currently the [advance search](http://search.maven.org/#advancedsearch%7Cgav) has capabilities that this SPA does not, we require to investigate whether this is still needed.

These capabilities include:
- Searching by Classpath/Classname?
- Searching by SHA

Good things to check : 
- Google analytics for current site.
- User check (maybe Joel would be best to confirm with), on what is being used.

**Acceptance Criteria**
- implement advance search capabilities
- bounce around idea's on UI for this.

Please leave a comment or reaction to this issue if you'd benefit from this functionality!

**Comment by fbricon** [comment]
Some years ago, I started to implement an artifact search in m2e, based on the currently exposed solr API (See https://bugs.eclipse.org/bugs/show_bug.cgi?id=478647, https://github.com/fbricon/m2e-core/commit/f46db07ed2762c2e3573e4178127737884ab7419)

I'm not interested in the UI part of the Advanced search capabilities much, but definitely in some REST endpoints. What I'd like to see, available for 3rd party tools:
- groupId search: currently the search returns N artifacts of the 1st groupIds matching a search query, but we're really interested in the actual N groupIds. See https://github.com/fbricon/m2e-core/commit/f46db07ed2762c2e3573e4178127737884ab7419#diff-2f9c1bb9a3e21f1fc5d0925c48b9f55eR67
- artifact search per artifactId and optional groupId
- classifier search per artifactId, groupId and version
- version search per artifactId, groupId

**Comment by DarthHater** [comment]
Thanks for the info @fbricon ! The work to do it won't likely be a part of this project (it'll be on the backend portion that powers all this), I'll check with the people working on that and see what they think!

**Comment by fbricon** [comment]
@DarthHater ok thanks. Would be nice to have an issue tracker for the backend too ;-)

**Comment by SirMaster** [comment]
We now support advances search on beta.

See here a small demo : 
[advanced-search.mp4.zip](https://github.com/sonatype-nexus-community/search-maven-org/files/2015464/advanced-search.mp4.zip)
