### ISSUE TITLE
Move Beta site to Production

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/search-maven-org#10]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Ultimately, to move this new site to the production url, instead of the current beta url

* **What feature or behavior is this required for?**
Mostly just getting more people to use this site!

* **How could we solve this issue? (Not knowing is okay!)**
There are a number of ways to do this, a few ideas before we got started are to:
- setup a way to A/B test
- setup a way to redirect based on User Agent
- do some analysis of the current Google Analytics data
- ????

* **Anything else?**

**Comment by ebourg** [comment]
It looks like the new site is now live, and unfortunately I find its usability inferior to the classic search engine:
* The search result doesn't fit vertically on a single page, scrolling is a pain. Please make it more compact.
* The artifact type are hidden behind a drop down menu, please keep direct download links for the types available
* The layout is clearly designed for smartphones, but I suspect the search engine is mostly used from computers by developers, so a real table with columns would be more convenient.

**Comment by DarthHater** [comment]
@ebourg that's great feedback, we are actually already internally talking about the scrolling. The site itself wasn't designed clearly for smartphones, most of us working on it are looking at it on a desktop, but we also made it a bit more mobile friendly in the process. @SirMaster and I invited you to attend our public bi-weekly hangout (it'll be tomorrow morning, I invited you to a gitter where we discuss it), glad to chat about it, as we already have been.

I'd like to close this issue as it's mainly related to moving the site from one URL to another, but I don't want to close it until you've created a different issue related to your feedback (as I think those could be distinct issues others could support/weigh in on), and it might improve the visibility of them to do so. Do you mind creating new issues for your feedback so I can close this one?

As well, we have left a link to the classic search for you to use in the meantime, while we collect feedback and ultimately drive towards perfection. It's available at: https://search.maven.org/classic/ in case you didn't see the link on the new site.

**Comment by DarthHater** [comment]
Closing in favor of creation of issues, @ebourg
