### ISSUE TITLE
Error 403 , when I want download dependencies 

### ISSUE THREAD

**Issue by mellis314** [sonatype-nexus-community/search-maven-org#118]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I trying to download serenity bdd Junit dependencies

Here is the screenshot : https://prnt.sc/r02b2f

* **What feature or behavior is this required for?**

I created maven project using serenity bdd archetype.

* **How could we solve this issue? (Not knowing is okay!)**
Please let me know how can I solve this issue, Thanks!

* **Anything else?**

**Comment by SirMaster** [comment]
@mellis314 thank you for logging a ticket with us, but this completely has nothing to do with this project. This project is specifically related to the Front End of http://search.maven.org/. Which shows the hosted artifacts of https://repo1.maven.org/. 

Your screenshot indicates that the repository you use is jcenter.bintray.com, so you might have to check with them. It does appear it's available. https://bintray.com/bintray/jcenter/org.slf4j%3Aslf4j-simple/1.7.7

If you are unable to solve it, you might try to switch to repo1.maven.org as your repository which also has that version:
https://search.maven.org/artifact/org.slf4j/slf4j-simple/1.7.7/jar
