### ISSUE TITLE
How to get dependencies of a given artifact using this API?

### ISSUE THREAD

**Issue by pramodya1994** [sonatype-nexus-community/search-maven-org#122]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Trying to get dependencies of a given artifact which you have displayed here.
<img width="1680" alt="Screenshot 2020-03-10 at 13 49 24" src="https://user-images.githubusercontent.com/19742678/76292938-29153300-62d6-11ea-8c1d-809b40cbcfcb.png">
I want to know the API definition for this to get these dependencies.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by isk-sonatype** [comment]
There is no API for that, the client just downloads https://search.maven.org/remotecontent?filepath=com/google/oauth-client/google-oauth-client-assembly/1.30.6/google-oauth-client-assembly-1.30.6.pom and parses XML (it doesn't resolve properties and parent POM)

**Comment by SirMaster** [comment]
@pramodya1994 based on @isk-sonatype comment I believe we can/should close this. Please let us know if you have any other questions in the future.
