### ISSUE TITLE
Can't see artifact ids on Chrome/Win10

### ISSUE THREAD

**Issue by bseib** [sonatype-nexus-community/search-maven-org#126]
* **What are you trying to do?**

I'm looking at: 
https://search.maven.org/artifact/com.google.oauth-client/google-oauth-client-assembly/1.30.6/pom

I'm getting ready to copy/paste the artifact id into my gradle/kotlin config.

However, the horizontal scrollable divs have scroll bars that cover up the content, so I cannot see the artifact id. This is chrome on Win10.

![image](https://user-images.githubusercontent.com/1313561/79687954-c427f380-8218-11ea-8f0e-98bd9b133fe7.png)

Should be an easy CSS fix.

**Comment by SirMaster** [comment]
@bseib my apologies for the delayed reply. We have been doing some testing and couldn't directly reproduce it. On Win 10 in Chrome we are able to see it properly.

A screen shot from Chrome on Win 10:
![2020-05-15_1635](https://user-images.githubusercontent.com/3211896/82094269-8dc38400-96b1-11ea-87b9-a8cf60c08d12.png)

Additionally we tested the following browsers versions on Win 10:
IE 11.836.18362.0
Chrome 81.0.4044.138
Edge 81.0.416.72
FF 76.0

If this is still an issue for you would you be able to test some of the other browsers and versions? and/or are you willing to maybe submit a PR that fixed it for you?

**Comment by bseib** [comment]
I reloaded the page just now, and it renders the horz scrollbar without covering the content now:

![image](https://user-images.githubusercontent.com/1313561/82095662-801bf780-96cd-11ea-916f-6a9be058c388.png)

Dunno what happened, if the min-height was changed, or if it was just squirrels chewing on my network cable. ¯\_(ツ)_/¯  Seems to work okay now.

**Comment by SirMaster** [comment]
@bseib 

> or if it was just squirrels chewing on my network cable

We unfortunately can't help with that, but can recommend you several natural enemies for squirrels if desired ;-) .

Glad it works again!
