### ISSUE TITLE
Search doesn't work for some artifacts with core=gav

### ISSUE THREAD

**Issue by DixonDs** [sonatype-nexus-community/search-maven-org#128]
An example of a request that doesn't return data: https://search.maven.org/solrsearch/select?core=gav&q=g:%22org.apache-extras.beanshell%22%20AND%20a:%22bsh%22

The following request without core=gav returns data: https://search.maven.org/solrsearch/select?q=g:%22org.apache-extras.beanshell%22%20AND%20a:%22bsh%22

**Comment by SirMaster** [comment]
@DixonDs thank you for the report, this project is specifically related to the Front End of Search Maven Org.

I would suggest to log this as an issue on https://issues.sonatype.org/browse/MVNCENTRAL for further investigation by our developers.
