### ISSUE TITLE
Wrong Artifact version,pls help us delete this wrong version

### ISSUE THREAD

**Issue by WANGMUXIAN** [sonatype-nexus-community/search-maven-org#138]
hello, we publish a wrong 4.0.11 version of tencentcloud-sdk-java, we have invalidate this version and do not want to user see this version, so can help me delete this version in sonatype, thank you very much.

**Comment by SirMaster** [comment]
@WANGMUXIAN this project is specifically about the Front-End of Search Maven and not specifically about the publishing part. 

For issues related to the contents of Maven Central (repo1.maven.org) and, by extension, the data backing search.maven.org, you can create a ticket here:

https://issues.sonatype.org/projects/MVNCENTRAL
