### ISSUE TITLE
Progressive Web App version of search.maven.org

### ISSUE THREAD

**Issue by DarthHater** [sonatype-nexus-community/search-maven-org#14]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
The new site is Responsive, but potentially we can implement a Progressive Web App version of it.

* **What feature or behavior is this required for?**
I am not 100% sure, but it came up in an idea generation session for the site.

* **How could we solve this issue? (Not knowing is okay!)**
Implement it :)

* **Anything else?**

**Comment by SirMaster** [comment]
This has been done as part of improvements for #39 

At the time of this writing we know score really good in the lighthouse audit : 

<img width="1187" alt="screen shot 2018-08-23 at 4 35 12 pm" src="https://user-images.githubusercontent.com/3211896/44557268-a1b39f00-a6f2-11e8-9ba8-925e41e79367.png">
