### ISSUE TITLE
JUnit v5.8.0 missing from search/lists

### ISSUE THREAD

**Issue by nhojpatrick** [sonatype-nexus-community/search-maven-org#152]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**

https://search.maven.org/search?q=g:org.junit%20AND%20a:junit-bom%20AND%20v:5.8.0

Or;
https://search.maven.org/search?q=g:org.junit%20AND%20a:junit-bom

Neither list the 5.8.0 release

* **What feature or behavior is this required for?**

Viewing newer releases, 5.8.0 and 1.8.0 appear to be missing.

* **How could we solve this issue? (Not knowing is okay!)**

Check search is updating from released artifacts.

* **Anything else?**

**Comment by sormuras** [comment]
Created some screenshots to show what is shown: https://twitter.com/sormuras/status/1438038269133037574

- `org.junit.jupiter`

![image](https://user-images.githubusercontent.com/2319838/133388688-217360c6-79d3-4b3f-b256-1ca586000b22.png)


- `org.junit.platform`

![image](https://user-images.githubusercontent.com/2319838/133388563-48b1035f-5fe5-4933-84fb-1ca82cec3b0d.png)

**Comment by SirMaster** [comment]
Hi @sormuras thank you for getting in touch with us, the links you send do show the 5.8.0 versions. Maybe I am not seeing/reading correctly what is incorrect.

![Screen Shot 2021-09-15 at 9 23 40 AM](https://user-images.githubusercontent.com/3211896/133471812-246e7c9e-3f9d-4b58-9609-5976430dda1b.png)

Looking at your screen shots, the first screen shot of `org.junit.jupiter` show that the second item in the list is version `5.8.0`. The second screen shot for `org.junit.platform` seems different from when I search. The 4th and 5th item in the list have version 1.8.0.
![Screen Shot 2021-09-15 at 9 27 36 AM](https://user-images.githubusercontent.com/3211896/133472447-8040363a-eb48-470b-b832-ef69d355c9a3.png)

Let me know if I am seeing it wrong or maybe am understanding it incorrectly.

**Comment by SirMaster** [comment]
I think, as SonatypeOps, mentioned in the twitter response this could have been because of a lag in publishing.

**Comment by sormuras** [comment]
Yeah, it seems the index is updating slowly and its getting more and more up-to-date as we type.

**Comment by nhojpatrick** [comment]
Might want to redesign the update or release process to reduce the lag, as it's strange what is showing and what isn't.
