### ISSUE TITLE
Artifact missing from index

### ISSUE THREAD

**Issue by evant** [sonatype-nexus-community/search-maven-org#158]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I've published version 0.25 of an artifact to maven central https://repo1.maven.org/maven2/com/willowtreeapps/assertk/assertk/0.25/ but when you search for it https://search.maven.org/search?q=g:com.willowtreeapps.assertk it's not showing up. (It says the latest version is 0.24). It does resolve correctly as a dependency. 

* **What feature or behavior is this required for?**
I would expect it to should up so users are able to find the latest version in a search.

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**

**Comment by toddobryan** [comment]
It looks like this is happening in multiple places. 

If you click on the badge for https://kotest.io/ , which should be at v5.0.0.M3, it only finds v1.1.1

**Comment by tomasbjerre** [comment]
Same happeing with my library, new versions are released:
https://repo1.maven.org/maven2/se/bjurr/springresttemplateclient/spring-resttemplate-client/

The web still shows 1.1.0 as latest:
https://search.maven.org/artifact/se.bjurr.springresttemplateclient/spring-resttemplate-client/1.1.0/jar

**Comment by mvitz** [comment]
Same is true for the latest Spring Boot releases 2.7.1 and 2.6.9 https://search.maven.org/artifact/org.springframework.boot/spring-boot-starter-parent only lists 2.7.0 and 2.6.8

**Comment by julian-alarcon** [comment]
Hi! Sorry for the issues in your current projects @evant @toddobryan @tomasbjerre @mvitz . I just found out this ticket, please keep in mind that this project is specifically for the app in use not the data generated/used/published in https://search.maven.org.

Please check the current Documentation related to support on your projects hosted in Maven Central Repository https://central.sonatype.org/pages/support/#producers

As you have issues with data in search.maven.org, you probably need to open a Publishing Support ticket from here: https://issues.sonatype.org/secure/CreateIssue.jspa?issuetype=11003&pid=10134

This ticket will be closed but we will keep an eye on your newer tickets in [Jira](https://issues.sonatype.org/).

**Comment by mvitz** [comment]
Just FYI I already created https://issues.sonatype.org/browse/MVNCENTRAL-7497 (currently private) after being aware that this might be the wrong place.

**Comment by evant** [comment]
@mvitz thanks for the tip, created https://issues.sonatype.org/browse/MVNCENTRAL-7511
