### ISSUE TITLE
spring-boot-dependencies 2.6.0 doesn't show any content

### ISSUE THREAD

**Issue by hennr** [sonatype-nexus-community/search-maven-org#159]
**What are you trying to do?**

I searched for spring-boot-dependencies and clicked on the 2.6.0 release, ending on this empty page:
https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies/2.6.0/pom

A click on the browse button in the upper right corner works, the download button is broken though.

Another thing that troubles here is that when you switch to a different release, say 2.5.7 and switch back to 2.6.0 again, there is the pom from 2.5.7 shown for the 2.6.0 release.

You can find a short discussion in this topic here already:
https://github.com/spring-projects/spring-boot/issues/28698

**Comment by SirMaster** [comment]
@hennr thank you for creating this. It appears that the underlying BE services is unable to retrieve the correct data for version 2.6.0, i'll checkin with our developers on that.

Additionally I think we can/should handle that a bit more gracefully on the UI when we can retrieve it. I'll take a look at that as well (likely not as part of this issue).

**Comment by hennr** [comment]
Thanks, this is good news.
I'll stay tuned!

**Comment by SirMaster** [comment]
@hennr hope you had a good weekend. 

We found the cause, we were applying some aggressive cache for the 404 returned on retrieving the data. We busted the cache, and all should be good again, which my testing confirmed.

Hope you have a great day!

**Comment by hennr** [comment]
Thanks for taking care and coming back!

**Comment by hennr** [comment]
Hi @SirMaster, same issue for spring-boot 2.6.2: https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies/2.6.2/pom
Could you check your cache again?

**Comment by jorlina** [comment]
@hennr Thanks for the report.  We've purged our caches for that particular artifact.  The details should now show up correctly in the search results.  We will need to do some digging on our side to see why this seems to keep happening.

**Comment by hennr** [comment]
Hello @jorlina 
the problem seems to happen again for spring-boot 2.6.6
The search does not show the new version as well (yet?)
https://search.maven.org/artifact/org.springframework.boot/spring-boot-dependencies

**Comment by jorlina** [comment]
It took a while but 2.6.6 should be there now.
