### ISSUE TITLE
The search couldn't find org.apache.santuario:xmlsec version 2.2.3

### ISSUE THREAD

**Issue by omerblecher** [sonatype-nexus-community/search-maven-org#164]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
*
org.apache.santuario:xmlsec version 2.2.3 exists in Maven central repository 
https://repo1.maven.org/maven2/org/apache/santuario/xmlsec/2.2.3/

However, when I search for it, I get not results: https://search.maven.org/classic/#search%7Cga%7C1%7Cg%3A%22org.apache.santuario%22%20AND%20a%3A%22xmlsec%22%20AND%20v%3A%222.2.3%22

I even try to search for hash 216237777d6371fa618d8b8a51a53a1c295291f5 that exists there:
https://repo1.maven.org/maven2/org/apache/santuario/xmlsec/2.2.3/xmlsec-2.2.3.jar.sha1

But again, the search returns no results at all

https://search.maven.org/solrsearch/select?q=1:%22216237777d6371fa618d8b8a51a53a1c295291f5%22&rows=100&wt=json

* **What feature or behavior is this required for?**

We need it to find if a version of specific artifact exists in Maven central or to associate hash value to a library

* **How could we solve this issue? (Not knowing is okay!)**

Please check this bug, why I don't get result for library that exists

* **Anything else?**

**Comment by jorlina** [comment]
We had to schedule a job to re-index these artifacts and add them to search.maven.org.  Can you confirm that they appear in search results now @omerblecher?

**Comment by omerblecher** [comment]
Yep, now it is found, Thanks!
