### ISSUE TITLE
Wrong last version for library com.fasterxml:alto-xml

### ISSUE THREAD

**Issue by mavek87** [sonatype-nexus-community/search-maven-org#188]
* **What are you trying to do?**

I'd like to report that the response of a REST call for the library **com.fasterxml:alto-xml** does not match the expectations. The last version is wrong (1.3.1 instead of 1.3.2)

Calling https://search.maven.org/solrsearch/select?q=g:com.fasterxml+AND+a:aalto-xml&core=gav&rows=50&wt=json does NOT return the real last version which should be 1.3.2 instead of 1.3.1 

as you can check here: https://central.sonatype.com/artifact/com.fasterxml/aalto-xml/1.3.2/versions

* **How could we solve this issue? (Not knowing is okay!)**

Am I doing some mistake with the REST call or is it some sort of bug?

**Comment by mavek87** [comment]
The issue can probably be closed now. I contacted the sonatype support by mail and they forced the "manual refresh" of the library and now the REST call result looks ok

**Comment by 0xDrogon** [comment]
I found another library with this issue: https://github.com/sonatype-nexus-community/search-maven-org/issues/190
@mavek87 which email address did you use to contact sonatype support?
