### ISSUE TITLE
Snippets for non-jar dependencies ignore type

### ISSUE THREAD

**Issue by fbricon** [sonatype-nexus-community/search-maven-org#19]
* **What are you trying to do?**
Copy snippets for non-jar Maven dependencies

* **What feature or behavior is this required for?**
Directly pasting snippets to a pom.xml  (or other build files)

* **How could we solve this issue? (Not knowing is okay!)**
Currently, all artifacts, regardless of their packaging, display dependency snippets as if they were jars.
For instance, https://search.maven.org/beta/artifact/org.eclipse.hudson/hudson-war/3.3.3/war has a war packaging and yet you get:
```xml
<dependency>
  <groupId>org.eclipse.hudson</groupId>
  <artifactId>hudson-war</artifactId>
  <version>3.3.3</version>
</dependency>
```

I expect the xml snippet to be:
```xml
<dependency>
  <groupId>org.eclipse.hudson</groupId>
  <artifactId>hudson-war</artifactId>
  <version>3.3.3</version>
  <type>war</type>
</dependency>
```

Problem is probably the same for other build system snippets, but I mostly use Maven so I wouldn't know.

**Comment by DarthHater** [comment]
Should be resolved as a part of #20 , I'll let you know when we get it deployed!
