### ISSUE TITLE
Improve behavior to search both group and artifact ids

### ISSUE THREAD

**Issue by kjjaeger** [sonatype-nexus-community/search-maven-org#2]
When testing the search on the beta site here: https://search.maven.org/beta/search I noticed a couple of things.  It seems that if you do a search with multiple terms like "apache collections" I get no results returned.  I know that I can use operators like g: and a: but it would be better if the default behavior would search for terms across the group and artifact ids without the need for the operators.

**Comment by DarthHater** [comment]
I think this was a limitation of Solr (how we implemented it anyways) from what I remember, but we were playing with some other options. Thanks for filing this!

**Comment by SirMaster** [comment]
@kjjaeger I believe this was addressed with fixes in the recent past (don't remember exactly what fix number)

I.e. see below a search with multiple terms "apache collections":
<img width="1674" alt="screen shot 2018-08-23 at 4 43 34 pm" src="https://user-images.githubusercontent.com/3211896/44557556-da07ad00-a6f3-11e8-9c0b-1c3db87bab1e.png">
