### ISSUE TITLE
Implement Advance Search Builder

### ISSUE THREAD

**Issue by MrIndiaDev** [sonatype-nexus-community/search-maven-org#24]
* **What are you trying to do?**
Implement Advance Search Builder

* **What feature or behavior is this required for?**
Initially, it could be responsive version of existing advance search and can be further improved for better User Experience.

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**
Please refer 
https://github.com/sonatype-nexus-community/search-maven-org/issues/1#issuecomment-396556544

**Comment by SirMaster** [comment]
Closing as implemented in https://github.com/sonatype-nexus-community/search-maven-org/issues/1
