### ISSUE TITLE
Adding in footer elements

### ISSUE THREAD

**Issue by tyanko1** [sonatype-nexus-community/search-maven-org#28]
* **What are you trying to do?**
Add in the various footer elements from the existing search.maven.org site including:
- Privacy Policy 
- Terms of Service
- About Sonatype
- Apache Maven resources 

* **What feature or behavior is this required for?**
providing users easy access to to information related to Sonatype's usage policies and company information. 

* **How could we solve this issue? (Not knowing is okay!)**
index.html updates 

* **Anything else?**

**Comment by TimvdLippe** [comment]
This appears to be fixed now: 
![image](https://user-images.githubusercontent.com/5948271/43909856-9bd5dc30-9bfb-11e8-87bf-f17744103f28.png)

**Comment by DarthHater** [comment]
Yep! Thanks for commenting @TimvdLippe , got a bit of cleanup to do!
