### ISSUE TITLE
URL scheme results in 404 in nginx

### ISSUE THREAD

**Issue by TimvdLippe** [sonatype-nexus-community/search-maven-org#29]
* **What are you trying to do?**
I was inspecting one of our artifacts in the central repository. When I found the artifact, I wanted to update the URL in our documentation. I wanted to update the URL, as I discovered that the previous URL mechanism is broken. Our previous URl was http://search.maven.org/#artifactdetails%7Corg.mockito%7Cmockito-core%7C1.10.19%7C (see https://github.com/mockito/mockito.github.io/blame/master/_posts/2000-01-01-intro.md#L35), but that URL seems to be broken now. Therefore, the new URL should be https://search.maven.org/artifact/org.mockito/mockito-core/1.10.19/jar However, opening that directly in the URL bar results in:

```
404 Not Found
nginx/1.12.1
```

I was able to land on this URL by going to search.maven.org, search for our artifact (`org.mockito:mockito-core`), select the latest version (at the time of writing 2.21.0) and then in the dropdown select 1.10.19. Note that in-client navigation works. E.g. back-/forth-buttons do work. Just not the initial URL navigation.

* **What feature or behavior is this required for?**
To be able to link directly to our artifact on our documentation website http://site.mockito.org/.
* **How could we solve this issue? (Not knowing is okay!)**
Make sure that when opening URLs, the nginx server can correctly resolve the location.
* **Anything else?**
n/a

**Comment by SirMaster** [comment]
@TimvdLippe thank you for logging this! We are working on the bookmarkable issue right as we speak and hope to correct asap! 

I think during all the happening from moving out of beta, we unfortunately missed this.

**Comment by TimvdLippe** [comment]
@SirMaster That's great to hear! I will be patiently waiting for the fix 😄 Sidenote: props on the new design! A lot better than the previous one 😉

**Comment by DarthHater** [comment]
This should be fixed! I'll close the issue once you confirm.

**Comment by TimvdLippe** [comment]
Confirmed it works :tada: Thanks for the speedy fix!
