### ISSUE TITLE
Search results should be sorted by popularity

### ISSUE THREAD

**Issue by fbricon** [sonatype-nexus-community/search-maven-org#3]
* **What are you trying to do?**
Searching for very common library, eg. hibernate, doesn't return org.hibernate:hibernate as first result
<img width="704" alt="screen shot 2018-04-02 at 9 03 08 pm" src="https://user-images.githubusercontent.com/148698/38223608-c26c5de4-36b9-11e8-926b-6240934bcae9.png">

One needs to scroll down to find it.

* **What feature or behavior is this required for?**
Find the latest org.hibernate:hibernate lib

* **How could we solve this issue? (Not knowing is okay!)**
Search results should be sorted by popularity/download numbers, with the most popular results on top.

* **Anything else?**
That'll be all for now

**Comment by SirMaster** [comment]
@fbricon thank you again for creating this. Looking further into this we found that this would require some Back End changes to allow sorting on specific criteria.

This project is specifically related to the Front End of Search Maven Org, when we start looking into improving our Back End servers we will hopefully address this as well.

For now closing this, I did add a specific label that allows us to come back and review any changes we need to make once we updated out Back End.
