### ISSUE TITLE
Stats show size is 0MB

### ISSUE THREAD

**Issue by joedragons** [sonatype-nexus-community/search-maven-org#30]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Looking at https://search.maven.org/stats

* **What feature or behavior is this required for?**
Unsure, but I doubt it should be 0.  I assume the size is the total amount in all of search.maven?

* **How could we solve this issue? (Not knowing is okay!)**
(see above)

* **Anything else?**
Screenshot:
![screen shot 2018-08-09 at 10 38 37 am](https://user-images.githubusercontent.com/9559205/43906235-c8cf04fe-9bc0-11e8-8e98-b7fd4fdd0481.png)

**Comment by jorlina** [comment]
We used to calculate that number by walking the filesystem and storing the total directory size of everything under ./maven2 in one of the underlying search indexes.  We no longer rely on a traditional filesystem or the index that used to hold that total size.  However, I think it should be relatively straightforward to get a good-enough size of all the artifacts, which we store in AWS S3, by using either the S3 or Cloudwatch metrics API.

**Comment by DarthHater** [comment]
Resolved in #63 , thanks @simon04 !
