### ISSUE TITLE
Search box overlaps 'quick stats' button

### ISSUE THREAD

**Issue by mcculls** [sonatype-nexus-community/search-maven-org#32]
Noticed this with Chrome 67.0.3396.99 on OSX, but also happens to a lesser extent with Safari

<img width="1440" alt="screen shot 2018-08-09 at 18 46 28" src="https://user-images.githubusercontent.com/145851/43916200-ce5e811c-9c04-11e8-97cf-ba05abc4d701.png">

... unless it's intentional that the search icon is also doubling as a Q ;)

**Comment by SirMaster** [comment]
Working on this one right now!

**Comment by DarthHater** [comment]
Fixed internally, will roll out soon to prod, also we will export the code today too.
