### ISSUE TITLE
Automatically compute latest artifact version

### ISSUE THREAD

**Issue by TimvdLippe** [sonatype-nexus-community/search-maven-org#35]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I am trying to link to the latest version of our artifact. At the time of writing, this version is 2.21.0. However, in our documentation we do not want to hardcode this value, as we release often. Therefore, I would like to link to our latest version. Something along the lines of https://search.maven.org/artifact/org.mockito/mockito-core/latest/jar or maybe just https://search.maven.org/artifact/org.mockito/mockito-core/
* **What feature or behavior is this required for?**
To link from our documentation to the latest version on Maven central
* **How could we solve this issue? (Not knowing is okay!)**
Rewrite the url scheme to automatically compute the latest version and redirect to that instead.
* **Anything else?**

**Comment by SirMaster** [comment]
@TimvdLippe thanks for the great improvement idea! I have put out a PR to our team and am waiting for it to go through our review and build process.

I have followed your thought on directing from 
https://search.maven.org/artifact/org.mockito/mockito-core/ to ==> https://search.maven.org/artifact/org.mockito/mockito-core/ `latest-version` / `packaging of latest version`

Note that the forward slash at the end can be used but is not required.

**Comment by DarthHater** [comment]
This is a really cool idea and something we wouldn't have immediately thought of. Thanks for suggesting it @TimvdLippe !
