### ISSUE TITLE
Leiningen Artifact displayed incorrectly

### ISSUE THREAD

**Issue by thheller** [sonatype-nexus-community/search-maven-org#37]
https://search.maven.org/artifact/org.clojure/clojurescript/1.10.339/jar

```
Leiningen
[org.clojure}/clojurescript "1.10.339"]
```

There is an extra `}` in the group which should not be there.

Seems to happen for every artifact.

**Comment by SirMaster** [comment]
@thheller thank you for logging this!

It was corrected in https://github.com/sonatype-nexus-community/search-maven-org/pull/34, we have been waiting for a successful build to be pushed to the production server.

Which I have confirmed is now live. I will close this.

**Comment by thheller** [comment]
Teaches me for only searching in issues and not PRs.  Thanks.
