### ISSUE TITLE
Optimize website based on LightHouse audit

### ISSUE THREAD

**Issue by TimvdLippe** [sonatype-nexus-community/search-maven-org#39]
I ran a LightHouse audit on https://search.maven.org/ and there are some points of improvement. (If you want to run this audit yourself, see https://developers.google.com/web/tools/lighthouse/#devtools )

Most notably, there are quite some large resources that are also render-blocking (such as `main.js`, `polyfills.js` and `styles.css`). It would be great if they are not render-blocking, but simply progressively enhance the HTML that is sent over initially. Moreover, these resources do not have a caching strategy and will thus be refetched every single time. Since I saw you are hashing your files (nice!), consider putting a long caching strategy, e.g. https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/http-caching#cache-control

I also saw you are using Webpack. (I saw this in the generated build files, but I saw no reference to webpack in this repository. Where is this coming from?) Consider taking advantage of code splitting (https://webpack.js.org/guides/code-splitting/) to lazy-load or only load code when it is used. There is quite a lot of script pushed to the client, but I do not think you need all of it right away. If you lazy load the scripts that you do not need right away, but later, you cut down considerably the initial file load.

You can also take a closer look at what is actually in your bundle with tools like https://www.npmjs.com/package/webpack-bundle-analyzer to see what you are shipping to the user. There might be package that you are loading right now that are unnecessary or replaceable with small custom functions.

For example, you are loading a lot of polyfills even on browsers that do not require them. See https://github.com/sonatype-nexus-community/search-maven-org/blob/ec51bc29f7b92cff4583aefaf8941b40e7959863/src/polyfills.ts#L21-L35 which loads polyfill code that should only be loaded on IE, as all other browsers work just fine.

Lastly, there is a new technology called service-worker which can speed up your repeating customers. You can automatically generate these workers with tools like Workbox (https://developers.google.com/web/tools/workbox/).

**Comment by TimvdLippe** [comment]
I can try to build this project tomorrow and see what I can do!

**Comment by TimvdLippe** [comment]
So I did an initial investigation. Sadly, the problem is a well-known problem with the Angular CLI. Apparently the Angular CLI uses Webpack under the hood, which does not understand how to tree-shake imports. Therefore imports like `import { Component, isDevMode } from '@angular/core';` pull in the 500KB core bundle, even though only few parts are actually necessary.

I fear that an Angular expert has to take a stab at this, as I have not enough experience with Angular to tackle this problem :cry:

**Comment by DarthHater** [comment]
Apparently Angular DOES do Tree Shaking, but yeah, the big imports kinda prevent that from really working. I'll see if I can take a gander at this sometime, because you are right, I doubt we need absolutely the entire kitchen sink to run this.

**Comment by SirMaster** [comment]
@TimvdLippe and @DarthHater I have been looking into this and have made some good progress. I hope over the next couple of evenings to solidify the work and push it.

**Comment by TimvdLippe** [comment]
That is great news! Once you push it to this repo, please link the commit so that I can investigate. (Commit messages are always the same, making it impossible to read the git history in this repo :p )

**Comment by SirMaster** [comment]
@TimvdLippe I am not sure that will be possible... I am working of our private repo, maybe I can send you a patch? In the future we will likely do more work ourself on the public repo.

**Comment by SirMaster** [comment]
@TimvdLippe I pushed an update out to the production server

We have improved the lighthouse metrics in certain areas : 

![screen shot 2018-08-22 at 10 47 58 pm](https://user-images.githubusercontent.com/3211896/44506948-8b0f3880-a65d-11e8-9ecd-d9df62a74e30.png)

Some due to updated to code,
* lazy loading of routes/modules
* smaller images
* changes to the index.html

Others due to changes to our webserver 
* cache control (there is a little more we are gonna do here)
* gzip

From my test I can see performance has increased and lots of the request have smaller foot prints, there is for sure more that could be done, but I think that would be a harder task with the current frameworks we use. In short I followed several guides of Angular to help with increasing performance and the current deployment is the result of it.

**Comment by TimvdLippe** [comment]
@SirMaster Awesome work, yes a lot better! There are still some small improvements that can be made, but there has been a good amount of progress :tada:

**Comment by SirMaster** [comment]
@TimvdLippe yep more things to do, p.s. we disabled the caching for now. Hope to turn it on soon again, but we were having some issues with the classic site when it was turned on.

**Comment by SirMaster** [comment]
@TimvdLippe we enabled caching again for certain resources. With that and all the current changes, I believe that this is now handling most of the things currently possible for us to do.

I will close this issue, if you feel there are other specific areas that we can improve upon, feel free to create a new issues.

Once again a big thanks for taking the time to provide your feedback!
