### ISSUE TITLE
Invalid links to artifacts

### ISSUE THREAD

**Issue by plokhotnyuk** [sonatype-nexus-community/search-maven-org#4]
Searching of artifacts of our project https://search.maven.org/beta/search?q=g:com.github.plokhotnyuk.jsoniter-scala%20AND%20a:macros_2.11&core=gav returns a list of them with broken links like: https://search.maven.org/remotecontent?filepath=com/github/plokhotnyuk/jsoniter-scala/macros_2.11/undefined/macros_2.11-undefined.jar

**Comment by DarthHater** [comment]
What browser/os are you using? Mind adding a screenshot of where you see the link?

**Comment by plokhotnyuk** [comment]
They are in the Download column:
![image](https://user-images.githubusercontent.com/890289/38266541-41c68e10-3779-11e8-9602-acf11cde4103.png)

**Comment by SirMaster** [comment]
@plokhotnyuk I have been trying to reproduce what you are seeing, but search for `g:com.github.plokhotnyuk.jsoniter-scala AND a:macros_2.11` seems so show all the download links, I also have a bit of different result screen.

I did a small screen recording to show you how I see it :

[nexus-smo-issue-4.mp4.zip](https://github.com/sonatype-nexus-community/search-maven-org/files/1880945/nexus-smo-issue-4.mp4.zip)

**Comment by DarthHater** [comment]
I was able to replicate this yesterday @SirMaster via s.m.o/beta but I'll check locally today.

**Comment by DarthHater** [comment]
We have resolved this in our private FOR SONATYPE EYES ONLY REPO, the change should make it out today! Thanks for reporting @plokhotnyuk

**Comment by DarthHater** [comment]
Resolved in: 4743959d984216719f56a085f0706edc92a16e91
