### ISSUE TITLE
New search doesn't work at all

### ISSUE THREAD

**Issue by shevek** [sonatype-nexus-community/search-maven-org#40]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Search for e.g. apache cassandra

* **What feature or behavior is this required for?**
Finding the apache cassandra JAR

* **How could we solve this issue? (Not knowing is okay!)**
Make it return a nonempty set of results. The search autocompleter clearly knows it's there, but
1) the clicks in the search autocompleter do completely non-intuitive things, like NOT going to the thing I just clicked on
2) If I press the full search button, I get a results page which is empty and doesn't even contain the things from the autocomplete.

* **Anything else?**
It is definitely an issue that the UX on the site is now sufficiently bad that it's unusable. Whether my description of it is helpful is another matter, but seriously, did you actually try using this before you released it? It's utterly unusable.

**Comment by shevek** [comment]
A few more clicks and it's "Systems appears unavailable" anyway.

Going to https://www.mvnrepository.com/ and typing "apache cassandra" into the box returns apache cassandra as the top hit. I guess you could close this issue, as the user has a workaround: Use a different search engine.

**Comment by DarthHater** [comment]
Right, we left a link to the classic search for cases like this. You may have missed it, it's right under the search input box on the front page. Just in case you can't find it, here's a link to your query: https://search.maven.org/classic/#search%7Cga%7C1%7Capache%20cassandra%20JAR

We are taking a look at this. I'll let you know what we end up doing.

The links we are already looking at, something new should be rolling out fairly soon, @SirMaster has been playing around with a better view there.

**Comment by shevek** [comment]
An exemplary response to a ticket which was largely expostulation and incoherent flailing. Indeed, the new version is much more usable, thank you.

**Comment by DarthHater** [comment]
@shevek no problemo, here to help!
