### ISSUE TITLE
Linking to search results

### ISSUE THREAD

**Issue by ctubbsii** [sonatype-nexus-community/search-maven-org#43]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Navigate to: http://search.maven.org/#artifactdetails%7Corg.owasp%7Cdependency-check-maven%7C3.3.1%7Cmaven-plugin

* **What feature or behavior is this required for?**
Linking directly to specific searches from classic search.

* **How could we solve this issue? (Not knowing is okay!)**
Could preserve previous linking behavior to search results by implementing it in the new API or by rewriting the resource on the server side to redirect to whatever the new mechanism is to link directly to search results.

* **Anything else?**
I found the above link on the https://www.owasp.org/index.php/OWASP_Dependency_Check page, and it made me realize that the old method of linking to specific results no longer works. This is probably fine, provided there is another mechanism to link directly to search results... old links will have to just be updated over time.

**Comment by DarthHater** [comment]
The old links should work if you add /classic/ to them. We didn't put in a rewrite rule, as the # in the URL would mean we'd have to apply those links to /, making it problematic at best, as the new site is running at /.

As for the new site, links should work too:

https://search.maven.org/search?q=a:junit

That should show artifacts with junit in them for all of time, as far as I know!

**Comment by ctubbsii** [comment]
Yeah, I'm not too worried about some dubious use of linking having been broken. I just mostly wanted to make sure it wasn't an oversight and the breakage was expected/known. :smiley_cat: Feel free to close this issue.

**Comment by jorlina** [comment]
I'm going to go ahead and close this issue not just because you've gotten an answer to your question, but because #48 will likely be where we address restoring link compatibility.
