### ISSUE TITLE
Maven Central Badge has wrong format url

### ISSUE THREAD

**Issue by ian4hu** [sonatype-nexus-community/search-maven-org#45]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Copy the generated Maven Central Badge Markdown link and use it in README.md
(link format = http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22${groupId}%22%20a%3A%22${artifactId}%22, but in new version of search.maven.org the link format should be https://search.maven.org/search?q=g:%22${groupId}%22%20AND%20a:%22${artifactId}%22&core=gav)

* **What feature or behavior is this required for?**
Click the Maven Central Badge to open the search.maven.org and navigate to the specified artifact.

* **How could we solve this issue? (Not knowing is okay!)**
Update the link format to the right one, I will contribute a PR to fix it.

* **Anything else?**
none

**Comment by DarthHater** [comment]
Closing as I believe this was fixed in #46 , feel free to reopen if it isn't!
