### ISSUE TITLE
Restore backwards compatibility of search links

### ISSUE THREAD

**Issue by mrotteveel** [sonatype-nexus-community/search-maven-org#48]
A lot of projects link to the search.maven.org using the old link format, and the redesign of search.maven.org has broken all links of all projects that reference search.maven.org in this way. 

Please restore backwards compatibility by adding support for the old links back.

For example:

- Artifact detail link: https://search.maven.org/#artifactdetails%7Corg.firebirdsql.jdbc%7Cjaybird-jdk18%7C3.0.4%7C (should open https://search.maven.org/artifact/org.firebirdsql.jdbc/jaybird-jdk18/3.0.4/jar)
- Search link: http://search.maven.org/#search%7Cga%7C1%7Ccom.zaxxer.hikaricp (should link to https://search.maven.org/search?q=com.zaxxer.hikaricp or maybe https://search.maven.org/search?q=g:com.zaxxer%20AND%20a:HikariCP&core=gav)
- Other search options of classic

**Comment by mrotteveel** [comment]
Might be fixed with #47

**Comment by SirMaster** [comment]
@mrotteveel thank you for logging this, as you probably saw we closed/fixed this with #43, #46 and #47

We hope to release this soon to the production server.
