### ISSUE TITLE
 https://search.maven.org/beta page is empty on IE

### ISSUE THREAD

**Issue by tkleiber** [sonatype-nexus-community/search-maven-org#5]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
I try to open https://search.maven.org/beta/ on IE.
Webpage is empty.

* **What feature or behavior is this required for?**

* **How could we solve this issue? (Not knowing is okay!)**
Only IE for internet connections is available for me at work.

* **Anything else?**

**Comment by DarthHater** [comment]
Thanks for filing this! We will take a gander when we get a chance. What version of IE and what operating system version are you using?

**Comment by DarthHater** [comment]
I think we resolved this in 2cbc9273ab3f0520dd052bd3b4f666a7672c19e8 @tkleiber , we should have it out and deployed soon to test!

**Comment by DarthHater** [comment]
This should be fixed now @tkleiber , I'm going to close the issue, let me know if for some reason isn't working (you can reopen)!
