### ISSUE TITLE
Outdated "Latest Version" and "Updated" columns

### ISSUE THREAD

**Issue by gerib** [sonatype-nexus-community/search-maven-org#50]
Hi,

if I search for "a:commons-beanutils" the result shows:

> | commons-beanutils | commons-beanutils | 20030211.134440 | (21) | Nov 8, 2005 |  

If I select "(21)" to show all versions the latest actually is:

> | commons-beanutils | commons-beanutils | 1.9.3 | Sep 21, 2016 |

Kind regards,
Geri

**Comment by SirMaster** [comment]
@gerib thank you for logging this!

I have taken a look at the search results and compared it with the classic look, the results are exactly the same, meaning that this is not a regression on the Front End project but unfortunately on the result set we are getting back from our Back End servers.

I.e. : 
![screen shot 2018-08-23 at 9 05 30 am](https://user-images.githubusercontent.com/3211896/44537832-9d689100-a6b4-11e8-9fab-7e44b91f0d8d.png)
test

<img width="961" alt="screen shot 2018-08-23 at 9 05 08 am" src="https://user-images.githubusercontent.com/3211896/44537833-9e012780-a6b4-11e8-82aa-89b78ce33907.png">

When we start looking into improving our Back End servers we will hopefully address this as well.

For now closing this.

**Comment by keilw** [comment]
@SirMaster Will this be fixed at some point?
We already noticed that the pre-release `2.0-EDR` (common to Java standards under the JCP) caused resolution problems, but now that 2.0 of Unit-API was released, https://search.maven.org/search?q=g:%22javax.measure%22%20AND%20a:%22unit-api%22 still shows the previous stage `2.0-PRD` (Public Review Draft) as latest version by mistake. This view https://mvnrepository.com/artifact/javax.measure/unit-api hasn't even got the final 2.0 release. Another comparable API would be CDI: https://mvnrepository.com/artifact/javax.enterprise/cdi-api It had `1.1-PRD` before `1.1`, but there it seemed correct at the time. Has that stopped working recently?

**Comment by SirMaster** [comment]
@keilw I truly hope so, though I am not specifically involved with that part of the services, I'll check with some of the folks who are and see if they can comment.

**Comment by jorlina** [comment]
When you look at the full listing of versions, the sort takes into account the publish date, so 2.0 shows up at the top of this list:

https://search.maven.org/search?q=g:javax.measure%20AND%20a:unit-api&core=gav

However, publish date is not taken into account in the initial results view.  The version shown is based on, IIRC, string sorting, so 2.0-PRD sorts after 2.0.  Changing the sort would require changes on the backend, and we'd have to add an item to our backend backlog to scope out these changes.

**Comment by keilw** [comment]
In the list it seems correct, is there a way the common badges work with this "core=gav" flag, or is it just for list views? Otherwise all badges get confused when trying to resolve "latest".

**Comment by keilw** [comment]
Put a Bintray badge now in place: https://github.com/unitsofmeasurement/unit-api That one works ;-)
