### ISSUE TITLE
Design feedback for new website

### ISSUE THREAD

**Issue by stuart897** [sonatype-nexus-community/search-maven-org#55]
In the search results table, truncating Group ID and Artifact ID (if they're too long) makes it difficult to find what you're looking for - the classic site always displays the full text. Could the search table take up the full browser width, or at least show all the text in those columns?

In the search results table, could the date use the format day-month-year (like the classic site), or year-month-day? The USA date format is illogical. Also if the day is 1-9, I'd suggest displaying as "01", "02" for visual consistency.

How are the search results sorted? It would be nice if the table column headings were clickable to sort, if it's not lots of work.

Many thanks.

**Comment by SirMaster** [comment]
@stuart897 thank you for your feedback and my apologies for the delayed reply.

In reply to your requests : 
>  Could the search table take up the full browser width, or at least show all the text in those columns?

I will take another gander at this, though we are trying to provide a consistent look by not making the rows bigger then others for different lengths of IDs. Would you have a search query where you found this specifically hard to read? We can/could use up the fill browser width though we found that the look was very whitespaced and additionally the classic didn't fill the whole page.

> In the search results table, could the date use the format day-month-year (like the classic site).

Good catch! I will try to put out something for that really soon

> How are the search results sorted? It would be nice if the table column headings were clickable to sort, if it's not lots of work.

The search results are sorted the same as in classic. The sorting is controlled by the BE services and currently no easy changeable by the FE. It is for sure one of the major things we would like to correct first in a new and upcoming BE. See also https://github.com/sonatype-nexus-community/search-maven-org/issues/44

**Comment by SirMaster** [comment]
@stuart897 we pushed a correction for the date formatting.

**Comment by stuart897** [comment]
Thanks for adjusting the date. Regarding the search truncation, I believe I was searching for "beanutils" and 3 of the results are too long to be fully displayed.

**Comment by Dragas** [comment]
Can you push a feature where it redirects to classic search by default? The gradient looks out of place and photos are hard on data.

**Comment by SirMaster** [comment]
@stuart897 apologies for the delayed reply, to mitigate on some of the long names for group id and artifact id and still providing a consistent modern look by not making the rows bigger then others for different lengths of IDs, we are prefixing with ellipses now so that the most important information is still visible.

As an example (taken from my local dev): 

![screen shot 2018-12-27 at 3 02 55 pm](https://user-images.githubusercontent.com/3211896/50496954-8cc08280-09e8-11e9-9d1b-4d53d51c670e.png)

With that change being done (in the recent past) I will close this.

**Comment by SirMaster** [comment]
@Dragas thank you for your feed back, and my apologies for the long wait on a reply. Currently we don't redirect by default to the classic search, we have a a link "Classic Search" on the new landing page that will instantly direct you to the classic search in a new tab/window : 
<img width="328" alt="screen shot 2018-12-27 at 3 05 42 pm" src="https://user-images.githubusercontent.com/3211896/50497007-f93b8180-09e8-11e9-81ac-fc5127a05943.png"> or you can always bookmark https://search.maven.org/classic/ this link will be around for a while still.

The gradient look we used is similar to those on https://help.sonatype.com, https://community.sonatype.com and https://support.sonatype.com. This is done to have a consistent look and feel among the many services that Sonatype provides to the community.

Concerning the images used we have applied caching strategies to assure that we don't use data multiple times while still getting a nice modern look that reflects Sonatype and the community.
