### ISSUE TITLE
Better search capabilities

### ISSUE THREAD

**Issue by kristof9851** [sonatype-nexus-community/search-maven-org#62]
* **What are you trying to do?**
I want better search capabilities for https://search.maven.org/
Including:
- filters: be able to filter search results based on certain criteria. Like "updated>=2018-01-01"
- items-per-page should be customizable. Should allow me to view at least 100 per page. 

* **What feature or behavior is this required for?**
I want better search capabilities for https://search.maven.org/

* **How could we solve this issue? (Not knowing is okay!)**
See above

* **Anything else?**
No

**Comment by SirMaster** [comment]
@kristof9851 thank you for creating this, and my apologies for the delayed reply. Looking further into this we found that this would require some Back End changes to allow filtering on specific criteria.

This project is specifically related to the Front End of Search Maven Org, when we start looking into improving our Back End servers we will hopefully address this as well.

For allowing to view more then the current items-per-page in a customizable way, we current are following the same as what the classic is doing, but would not appose a customizable way to change that. A PR for it would be greatly appreciated :-) 

For now closing this, I did add a specific label that allows us to come back and review any changes we need to make once we updated out Back End.
