### ISSUE TITLE
"All versions" link impossible to select when latest version has long name

### ISSUE THREAD

**Issue by briandealwis** [sonatype-nexus-community/search-maven-org#67]
* **What are you trying to do?**

I was attempting to find out what versions of `com.google.guava:listenablefuture` were available.  This is a new artifact and includes a special version `9999.0-empty-to-avoid-conflict-with-guava`, plus a version `1.0`.  No matter how far I stretch my window, I can't get the "(NN)" link to show.

![screen shot 2018-10-30 at 1 37 55 pm](https://user-images.githubusercontent.com/202851/47738326-4c8f8e80-dc49-11e8-992f-b1223f8f1ece.png)

Workaround: append `&core=gav`.

* **How could we solve this issue? (Not knowing is okay!)**

Have the all-versions link separate?

**Comment by SirMaster** [comment]
@briandealwis thank you for logging this and my apologies for the delayed reply. We have corrected and are pushing this to production in the next little bit.

It will now look like : 
![screen shot 2018-12-27 at 3 37 32 pm](https://user-images.githubusercontent.com/3211896/50497558-841e7b00-09ed-11e9-9169-75bee40741c8.png)
