### ISSUE TITLE
Change "Gradle/Grails" to "Gradle" on artifact page

### ISSUE THREAD

**Issue by marcphilipp** [sonatype-nexus-community/search-maven-org#7]
* **What are you trying to do?**

Browsing to an artifact page and finding the instructions for how to use it with Gradle.

E.g. when opening https://search.maven.org/beta/artifact/org.junit.jupiter/junit-jupiter-api/5.2.0-M1/jar there's an entry for "Gradle/Grails" that shows the Grails logo and the URL of the Grails Gradle plugin. Gradle is used for a lot more things than Grails so this listing is confusing. A user might ask himself whether it will only work for Grails etc.

* **What feature or behavior is this required for?**

Instead, it should just show "Gradle", the Gradle logo, and use gradle.org as the URL.

* **How could we solve this issue? (Not knowing is okay!)**

see above :)

* **Anything else?**

In addition, it would be great if the URLs for all entries would be clickable.

Please let me know whether you think this makes sense. If so, I'd be happy to submit a PR.

**Comment by SirMaster** [comment]
@marcphilipp thanks for filing this! This appeared pretty simple, so took a quick look at.

I updated the naming and icon and made to text actual links, let me know if this is what you were having in mind :

![screen shot 2018-04-19 at 7 10 37 am](https://user-images.githubusercontent.com/3211896/38996921-1415f972-43a1-11e8-9757-fda494469e0f.png)

**Comment by eriwen** [comment]
Thank you @SirMaster! I noticed that there is a Gradle Kotlin DSL entry below. Would it make sense to clarify "Gradle" as "Gradle Groovy DSL"?

**Comment by DarthHater** [comment]
@eriwen @marcphilipp feel free to pop over a PR if you want, we'd love to get some contributions!

**Comment by SirMaster** [comment]
@DarthHater do note I already have a PR  for this :-) that's what the screen shot is from. So might save them some time/effort.
