### ISSUE TITLE
Include package information/staistics in results

### ISSUE THREAD

**Issue by mngola** [sonatype-nexus-community/search-maven-org#70]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
When searching for common libraries/classes the top results are not the most popular. We would like to be able to sort our results by popularity or number of downloads. Alternatively, we can develop our own sort if you can expose information about the classes in a package.

* **What feature or behavior is this required for?**
We are trying to automatically repair missing dependencies. We want to use search.maven.org to locate candidate JARs. Sorting results by popularity would improve our results.

* **How could we solve this issue? (Not knowing is okay!)**
Maven Central provides usage statistics on their page, could you pass that on when queried through search.maven.org. Searching through the website provides package information, could you document how to retrieve this through the API

* **Anything else?**
If this feature already exists, some documentation on how it works would be helpful. Thanks

**Comment by SirMaster** [comment]
@mngola this request has been made before in https://github.com/sonatype-nexus-community/search-maven-org/issues/3 and https://github.com/sonatype-nexus-community/search-maven-org/issues/44 and would require Back End changes to allow sorting on specific criteria.

This project is specifically related to the Front End of Search Maven Org, when we start looking into improving our Back End servers we will hopefully address this as well.

You did mention : 
> Maven Central provides usage statistics on their page, could you pass that on when queried through search.maven.org.

Could you say more about that? or an example/url of what you mean?

> Searching through the website provides package information, could you document how to retrieve this through the API

We currently don't provide a specific API for this.

For now I will add a label that allows us to come back and review any changes we need to make once we updated out Back End.

**Comment by mngola** [comment]
> Could you say more about that? or an example/url of what you mean?

![image](https://user-images.githubusercontent.com/11689242/51155439-82eeaa00-1845-11e9-83a7-27d86abaaff5.png)
On the site https://mvnrepository.com, you can see the usage statistics alongside the search results

Thanks.

**Comment by SirMaster** [comment]
@mngola thank you for the reply and example. We do not run mvn repository site, it appears to be hosted by someone in the community. They (as far as I can tell) do not use search.maven.org for their statistics or use our services for showing the popularity.

As mentioned before we would require some Back End changes to allow for this to be available,. Having added a label that allows us to come back and review any changes we need to make once we updated out Back End I will close this for now.
