### ISSUE TITLE
Add Bazel configuration block in artifact detail view

### ISSUE THREAD

**Issue by crimeminister** [sonatype-nexus-community/search-maven-org#71]
* **What are you trying to do?**

I would like to easily update a [Bazel](https://bazel.build/) `WORKSPACE` file with the details of a JAR file found through the search interface.

* **How could we solve this issue? (Not knowing is okay!)**

It would be great if there was an output block in the artifact detail page that contained the necessary configuration text for use with Bazel, e.g.

```
maven_jar(
  name = "some-dep",
  artifact = "com.example.foobar:some-dep:1.2.3",
  sha1 = "hash-goes-here",
)
```

**Comment by crimeminister** [comment]
@SirMaster That's the best source of information on the required format that I'm aware of. Thanks for the interest!

**Comment by SirMaster** [comment]
@crimeminister we added the block and hope to release it in the next little bit.

It will look like :
![image](https://user-images.githubusercontent.com/3211896/51698097-3da54780-1fbe-11e9-8089-a5c1d0383ff1.png)

**Comment by crimeminister** [comment]
Thanks, I'm looking forward to seeing this ship!

**Comment by SirMaster** [comment]
It's out in the wild now :-) 

example : https://search.maven.org/artifact/junit/junit/4.12/jar
