### ISSUE TITLE
Deprecated copy/pasteable for Gradle Kotlin DSL

### ISSUE THREAD

**Issue by Vampire** [sonatype-nexus-community/search-maven-org#72]
![grafik](https://user-images.githubusercontent.com/325196/53229840-9af7eb80-3685-11e9-89d8-4a420f376b38.png)

The Groovy example already uses the correct `implementation` configuration, but the Kotlin example uses the since years deprecated `compile` configuration, please also use `implementation` for Kotlin.

**Comment by Vampire** [comment]
When does this go live?
It still says `compile`.

**Comment by SirMaster** [comment]
It should have already.... https://github.com/sonatype-nexus-community/search-maven-org/pull/74, I believe I tested it as well. Will look into that, likely this Thursday.

**Comment by Vampire** [comment]
It is in master, yes, but it is not live

**Comment by SirMaster** [comment]
Hmm weird... will look into that. Thanks for catching that.

**Comment by SirMaster** [comment]
Should be all good now @Vampire
