### ISSUE TITLE
Search results are inconsistent with repo1.maven.org

### ISSUE THREAD

**Issue by hendychua** [sonatype-nexus-community/search-maven-org#73]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Searching for Java libraries on search.maven.org.  The results are inconsistent from repo1.maven.org. One example is `com.brettonw:bag-mongo`. When searching for this artifact, the results page shows there are 9 versions and the latest is `2.1.0`:
![screen shot 2019-03-04 at 3 15 39 pm](https://user-images.githubusercontent.com/1912245/53716638-863f0300-3e90-11e9-9654-0de2f3c9968d.png)
However, when you click on the results link (9), it shows 8 versions and `2.1.0` is missing:
![screen shot 2019-03-04 at 3 17 52 pm](https://user-images.githubusercontent.com/1912245/53716698-bb4b5580-3e90-11e9-8c02-f31355802e98.png)

The response from `http://search.maven.org/solrsearch/select?q=g:com.brettonw+AND+a:bag-mongo&rows=1000&core=gav&wt=json` also shows only 8 results.

A visit to http://repo1.maven.org/maven2/com/brettonw/bag-mongo/2.1.0/ shows that 2.1.0 is present.

* **What feature or behavior is this required for?**
Just searching.

* **How could we solve this issue? (Not knowing is okay!)**
If this is indeed a bug, it would be good to fix it. If it is expected behavior, document it in the README.

* **Anything else?**
Thank you for looking into this issue!

**Comment by SirMaster** [comment]
@hendychua my apologies on the delay. This does seem a bit strange. I also checked the classic version and it appears to behave the same. Based on that and the url used to retrieve the information this doesn't seem directly related to the Front End of Search Maven Org.

This project is specifically related to the Front End of Search Maven Org, that being said I will check with out Backend End engineers to comment on this here, if/when we know what is causing this.

Closing this for now.
