### ISSUE TITLE
utm to wgs84 ,Unserializable 

### ISSUE THREAD

**Issue by wangqianjia** [sonatype-nexus-community/search-maven-org#77]
I used this jar（proj4j-0.1.0.jar）, but many classes can't be serialized.So I have to modify the source code。。。

**Comment by wangqianjia** [comment]
![图片](https://user-images.githubusercontent.com/20453030/56282142-fce24800-6140-11e9-9fff-30c693797c76.png)

**Comment by SirMaster** [comment]
@wangqianjia this seems unrelated to the Front End of Search Maven Org, but with the actual use of the library proj4j.

I would suggest to do further research and/or get in touch on github with them here https://github.com/locationtech/proj4j
