### ISSUE TITLE
utm to wgs84, Reading the configuration file is too slow

### ISSUE THREAD

**Issue by wangqianjia** [sonatype-nexus-community/search-maven-org#78]
Using the stream to read the configuration file in the code and then finding the required coordinates through the loop, which is a very slow process

**Comment by wangqianjia** [comment]
![1555498331(1)](https://user-images.githubusercontent.com/20453030/56282632-2e0f4800-6142-11e9-925b-fe41b1dac3f0.png)

**Comment by SirMaster** [comment]
@wangqianjia this seems completly unrelated to the Front End of search maven org. 

Closing.
