### ISSUE TITLE
Newest version of our artifact is not available

### ISSUE THREAD

**Issue by labkey-ians** [sonatype-nexus-community/search-maven-org#79]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Search for the latest version of our client api.
https://mvnrepository.com/artifact/org.labkey/labkey-client-api
https://repo1.maven.org/maven2/org/labkey/labkey-client-api/
https://oss.sonatype.org/#nexus-search;quick~labkey
All Show 19.1.0

https://search.maven.org/search?q=g:org.labkey%20AND%20a:labkey-client-api&core=gav
shows 18.2

* **What feature or behavior is this required for?**
Search

* **How could we solve this issue? (Not knowing is okay!)**
no idea

* **Anything else?**

**Comment by SirMaster** [comment]
@labkey-ians this project is specifically about the Front-End of Search Maven and not specifically about the publishing part. It appear from looking at this that your latest version was not published to the Central Repository (or it has has not been indexed yet, this normally takes a couple of hours up to a day I believe).

**Comment by labkey-ians** [comment]
Best I can tell it has been published correctly, it shows in nearly every search but this one.

http://central.maven.org/maven2/org/labkey/labkey-client-api/
pushed on 2019-03-20 23:56

**Comment by SirMaster** [comment]
Yeah interesting how it is there. I will ask our engineers who handle this part of central. But as mentioned before this project is specifically about the Front-End of Search Maven. 

I will close this, but will keep you up to date on any news I get.

**Comment by jorlina** [comment]
For issues related to the contents of Maven Central (repo1.maven.org) and, by extension, the data backing search.maven.org, you can create a ticket here:

https://issues.sonatype.org/projects/MVNCENTRAL
