### ISSUE TITLE
Grid pagers don't changes results on the page

### ISSUE THREAD

**Issue by bradcupit** [sonatype-nexus-community/search-maven-org#80]
* **What are you trying to do?**
Use the grid's pager buttons on the bottom of search results. For example: [here](https://search.maven.org/search?q=g:com.google.guava%20AND%20a:guava-testlib&core=gav) and [here](https://search.maven.org/search?q=g:org.hibernate%20AND%20a:hibernate-core&core=gav). I'd like to navigate to page 2, page 3, etc.
* **What feature or behavior is this required for?**
I'd like to see results 21-40, or 41-60, etc.
* **How could we solve this issue? (Not knowing is okay!)**
I think this is a bug: I click the 'next page' button but the grid of results stays the same.
* **Anything else?**
The pager controls say "21 - 40 of 85" so that part's working, it's just not updating the results in the grid.

**Comment by SirMaster** [comment]
It appears the API is returning the same first 20 no matter the query. I will check with our API Engineers

e.g. the below all return the same:

https://search.maven.org/solrsearch/select?q=g:com.google.guava+AND+a:guava-testlib&core=gav&start=0&rows=20
https://search.maven.org/solrsearch/select?q=g:com.google.guava+AND+a:guava-testlib&core=gav&start=20&rows=20
https://search.maven.org/solrsearch/select?q=g:com.google.guava+AND+a:guava-testlib&core=gav&start=40&rows=20

**Comment by SirMaster** [comment]
I just classic, same behaviour.

**Comment by jorlina** [comment]
I've been doing some things to secure the classic APIs over the past couple days.  There appears to be more collateral damage than I expected!  Thankfully, this is a simple fix.  I'll push it out in the next 20-30 minutes.  Thanks @bradcupit for the report!

**Comment by jorlina** [comment]
@bradcupit The fix is out there.  It looks like pagination is working again for me in regular and classic search.  Please verify when you get the chance, and I'll close this issue.

**Comment by bradcupit** [comment]
@jorlina fixed!
