### ISSUE TITLE
Search on https://search.maven.org/ doesn't work properly

### ISSUE THREAD

**Issue by mvysny** [sonatype-nexus-community/search-maven-org#83]
* **What are you trying to do?**

Trying to search for `jetty-runner`. I type in `jetty-r` and the result list stays blank. I continue typing `jetty-runner` and a list of unrelated results pops up, e.g. `com.codingame.gameengine:runner`. However, jetty-runner is present in maven central: https://repo1.maven.org/maven2/org/eclipse/jetty/jetty-runner/

* **What feature or behavior is this required for?**

To download `jetty-runner` from official repo

**Comment by SirMaster** [comment]
@mvysny thank you for creating this, and my apologies for the delayed reply. Looking further into this we found that this would require some Back End changes, i.e. the search criteria that we pass back based on input returned 0 results for `jetty-r`.

This project is specifically related to the Front End of Search Maven Org, when we start looking into improving our Back End servers we will hopefully address this as well.

Do note when searching for `a:jetty-runner` I found several related versions.
