### ISSUE TITLE
Search by class name in a fuzzy match mode

### ISSUE THREAD

**Issue by RunxinXu** [sonatype-nexus-community/search-maven-org#85]
Hi!
* **What are you trying to do?**
I am trying to search by class name in a fuzzy match mode. For example, I try to search by "c:juni" and I can get the result of "junit". 
 
* **What feature or behavior is this required for?**
I wonder if any possibility to search in a fuzzy match mode? I used maven indexer in my project, but it seems to only support fuzzily search by class name in the index created from local repository(.m2), but not central repository.

* **How could we solve this issue? (Not knowing is okay!)**

* **Anything else?**
Thanks. It is a great project and helps a lot.

**Comment by SirMaster** [comment]
@RunxinXu I saw you asked this question in gitter to, this is currently not supported as fas as I can see, rhis project is specifically related to the Front End of Search Maven Org, when we start looking into improving our Back End servers we will hopefully address this as well.

For now closing this, I did add a specific label that allows us to come back and review any changes we need to make once we updated out Back End.

**Comment by SiRumCz** [comment]
Hi, is this feature implemented yet? I don't see any doc mentioning it.
